// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: proto/agents.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SelectAgentClient is the client API for SelectAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SelectAgentClient interface {
	SelectAgent(ctx context.Context, in *AgentName, opts ...grpc.CallOption) (*SelectedAgentReply, error)
}

type selectAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSelectAgentClient(cc grpc.ClientConnInterface) SelectAgentClient {
	return &selectAgentClient{cc}
}

func (c *selectAgentClient) SelectAgent(ctx context.Context, in *AgentName, opts ...grpc.CallOption) (*SelectedAgentReply, error) {
	out := new(SelectedAgentReply)
	err := c.cc.Invoke(ctx, "/SelectAgent/SelectAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelectAgentServer is the server API for SelectAgent service.
// All implementations must embed UnimplementedSelectAgentServer
// for forward compatibility
type SelectAgentServer interface {
	SelectAgent(context.Context, *AgentName) (*SelectedAgentReply, error)
	mustEmbedUnimplementedSelectAgentServer()
}

// UnimplementedSelectAgentServer must be embedded to have forward compatible implementations.
type UnimplementedSelectAgentServer struct {
}

func (UnimplementedSelectAgentServer) SelectAgent(context.Context, *AgentName) (*SelectedAgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectAgent not implemented")
}
func (UnimplementedSelectAgentServer) mustEmbedUnimplementedSelectAgentServer() {}

// UnsafeSelectAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SelectAgentServer will
// result in compilation errors.
type UnsafeSelectAgentServer interface {
	mustEmbedUnimplementedSelectAgentServer()
}

func RegisterSelectAgentServer(s grpc.ServiceRegistrar, srv SelectAgentServer) {
	s.RegisterService(&SelectAgent_ServiceDesc, srv)
}

func _SelectAgent_SelectAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelectAgentServer).SelectAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SelectAgent/SelectAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelectAgentServer).SelectAgent(ctx, req.(*AgentName))
	}
	return interceptor(ctx, in, info, handler)
}

// SelectAgent_ServiceDesc is the grpc.ServiceDesc for SelectAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SelectAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SelectAgent",
	HandlerType: (*SelectAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectAgent",
			Handler:    _SelectAgent_SelectAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agents.proto",
}
